# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r8Gl7U7oM0Ysq2OUuWKAS6PTae9Z_wL0
"""
import os
import numpy as np
import matplotlib.image as mpimg
str=os.getcwd()
f=open(str+"\\temp.txt", "r")
c=f.readlines()
name=c[0][c[0].rfind("\\")+1:c[0].rfind('.')]
f.close()

fichier=open(str+"\\resultimages\\"+name+"_result.txt", "r")
L=fichier.readlines()
lig=L[0].split("-")[0]
col=L[0].split("-")[1].split("\n")[0]
A=np.zeros((int(lig),int(col)))
A[0]
for i in range (1,len(L)):
  A[i-1]=list(map(float, L[i].split(" ")[:-1]))
print(A)
mpimg.imsave(str+"\\resultimages\\"+name+"_result.png", A,cmap="gray")
